#! /bin/bash -ex

export LC_ALL="en_US.utf8"
export LANG="en_US.UTF-8"

python3 -m portingdb --datadir $OPENSHIFT_REPO_DIR/data --db $OPENSHIFT_TMP_DIR/portingdb.sqlite -vv load

(echo FLUSHDB
 echo CONFIG SET maxmemory 101048576
 echo CONFIG SET maxmemory-policy allkeys-lru
) | redis-cli $REDIS_CLI
